---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check docker-compose
      ansible.builtin.command:
        cmd: docker-compose --version
      environment:
        PATH: /bin:/usr/bin:/usr/local/bin:/usr/libexec/docker/cli-plugins
